---
version: '2.1'

services:
  searchWebApp:
    build: ./searchwebapp
    image: demoapps/searchwebapp:1.0
    ports:
      - "80:80"
    container_name: webapp
    links:
      - searchDB
    depends_on:
      - dataseeder
    restart: always

  dataseeder:
    build: ./dataseeder
    image: demoapps/dataseeder:1.0
    container_name: dataseeder
    links:
      - searchDB
    environment:
      DB_CONNECTION_STRING: 'jdbc:mysql://searchDB:3306/test'
      DB_USERNAME: 'user'
      DB_PASSWORD: 'changeit'
    depends_on:
      searchDB:
        condition: service_healthy

  searchDB:
    image: mysql/mysql-server:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'changeit'
      MYSQL_DATABASE: 'test' 
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'changeit'
      MYSQL_ROOT_HOST: '%'
    container_name: database
    restart: always
