---
version: '2.1'

services:

  searchDB:
    image: mysql/mysql-server:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'changeit'
      MYSQL_DATABASE: 'test' 
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'changeit'
      MYSQL_ROOT_HOST: '%'
    container_name: database
    restart: always
